import type { DomainNode, SkillNode, RoleProfile, Relation, FailureScenario, CareerTransition } from "./types";

export const CENTER_DOMAIN: DomainNode = {
  id: "production-ai",
  slug: "production-ai-engineering",
  name: "Production AI Engineering",
  description: "The intersection of software, data, ML, LLMs, agents, and infrastructure at enterprise scale.",
  color: "#1d4ed8",
  x: 500,
  y: 500,
};

export const DOMAINS: DomainNode[] = [
  CENTER_DOMAIN,
  { id: "software", slug: "software-engineering", name: "Software Engineering", description: "APIs, systems design, testing, and maintainable code.", color: "#0f172a", x: 500, y: 180 },
  { id: "cloud", slug: "cloud-engineering", name: "Cloud Engineering", description: "AWS, Azure, GCP, networking, and managed services.", color: "#0369a1", x: 720, y: 260 },
  { id: "devops", slug: "devops", name: "DevOps", description: "CI/CD, containers, automation, and release engineering.", color: "#ea580c", x: 820, y: 440 },
  { id: "platform", slug: "platform-engineering", name: "Platform Engineering", description: "Internal developer platforms and self-serve tooling.", color: "#7c3aed", x: 760, y: 660 },
  { id: "data", slug: "data-engineering", name: "Data Engineering", description: "Pipelines, warehousing, streaming, and data quality.", color: "#0891b2", x: 580, y: 780 },
  { id: "ml", slug: "machine-learning", name: "Machine Learning", description: "Training, evaluation, and classical ML workflows.", color: "#059669", x: 360, y: 780 },
  { id: "nlp", slug: "nlp", name: "NLP", description: "Text processing, transformers, and language understanding.", color: "#65a30d", x: 200, y: 660 },
  { id: "mlops", slug: "mlops", name: "MLOps", description: "ML lifecycle automation from experiment to production.", color: "#1d4ed8", x: 160, y: 440 },
  { id: "genai", slug: "generative-ai", name: "Generative AI", description: "LLMs, fine-tuning, and generative applications.", color: "#c026d3", x: 200, y: 260 },
  { id: "rag", slug: "rag", name: "RAG", description: "Retrieval-augmented generation and knowledge systems.", color: "#db2777", x: 340, y: 180 },
  { id: "llmops", slug: "llmops", name: "LLMOps", description: "Operating LLMs in production with cost, eval, and governance.", color: "#9333ea", x: 660, y: 180 },
  { id: "aiops", slug: "aiops", name: "AIOps", description: "AI for IT operations, anomaly detection, and remediation.", color: "#d97706", x: 840, y: 580 },
  { id: "automation", slug: "ai-automation", name: "AI Automation", description: "Enterprise workflow automation with AI-native tools.", color: "#ea580c", x: 700, y: 740 },
  { id: "agents", slug: "agentic-ai", name: "Agentic AI", description: "Multi-agent systems, tool use, MCP, and orchestration.", color: "#4f46e5", x: 420, y: 820 },
  { id: "infra", slug: "ai-infrastructure", name: "AI Infrastructure", description: "GPU clusters, inference serving, and compute at scale.", color: "#475569", x: 240, y: 580 },
  { id: "fde", slug: "fde", name: "Forward Deployed Engineering", description: "Customer-facing delivery of AI solutions end-to-end.", color: "#b45309", x: 300, y: 380 },
  { id: "architecture", slug: "ai-architecture", name: "AI Architecture", description: "System design for enterprise AI platforms.", color: "#0f172a", x: 620, y: 380 },
  { id: "security", slug: "security", name: "Security", description: "Auth, compliance, guardrails, and threat modeling.", color: "#dc2626", x: 480, y: 680 },
  { id: "observability", slug: "observability", name: "Observability", description: "Metrics, logs, traces, and SLO-driven operations.", color: "#0284c7", x: 540, y: 320 },
];

function skill(partial: Omit<SkillNode, "level"> & { level?: SkillNode["level"] }): SkillNode {
  return { level: "technology", ...partial };
}

export const SKILLS: SkillNode[] = [
  skill({
    id: "kubernetes",
    slug: "kubernetes",
    name: "Kubernetes",
    domainId: "devops",
    parentId: "devops",
    x: 780,
    y: 400,
    summary: "Container orchestration for production workloads including ML and LLM inference.",
    what: "Container orchestration platform that schedules, scales, and heals distributed applications.",
    why: "Runs microservices, ML inference, and data platforms reliably at scale with declarative config.",
    usedIn: ["Microservices", "ML inference", "LLM serving", "GPU workloads", "Data platforms", "Internal developer platforms"],
    requiredByRoles: ["mlops-engineer", "llmops-engineer", "ai-infrastructure-engineer", "platform-engineer", "fde-engineer"],
    learnTopics: ["Pods", "Deployments", "Services", "Ingress", "Storage", "RBAC", "Scheduling", "HPA", "Helm", "Operators"],
    buildProject: "Deploy a production ML inference API with autoscaling and health probes.",
    productionReality: ["OOMKilled pods", "CPU throttling", "Bad probes", "ImagePullBackOff", "DNS failures", "PVC problems", "GPU fragmentation", "RBAC issues"],
    interviewPoints: [
      "Explain pod lifecycle and scheduling decisions",
      "How do readiness vs liveness probes differ?",
      "Debug a CrashLoopBackOff step by step",
      "How would you run GPU workloads on K8s?",
      "Describe networking: Service, Ingress, DNS",
    ],
    connectedSkills: ["docker", "linux", "terraform", "prometheus", "kserve", "helm"],
    prerequisites: ["docker", "linux"],
    alternatives: ["ECS", "Nomad", "Docker Swarm"],
    maturity: "L3",
    modes: {
      roadmap: "Learn after Docker and Linux. Core for MLOps, LLMOps, and AI infrastructure paths.",
      architecture: "Runs application and model workloads. Connects ingress, storage, GPU operators, and observability.",
      company: "Frequently observed in infrastructure-oriented AI and platform job descriptions (sample-based, not universal).",
      projects: "Deploy a scalable inference service with HPA, probes, and rolling updates.",
      interview: "Expect scheduling, networking, probes, autoscaling, and production troubleshooting depth.",
      career: "Gateway skill from DevOps into MLOps, LLMOps, and AI infrastructure roles.",
    },
    companyDemand: {
      level: "high",
      sampleNote: "Frequently observed across analyzed infrastructure-oriented postings (illustrative dataset).",
      roles: ["MLOps Engineer", "Platform Engineer", "AI Infrastructure Engineer", "SRE"],
      lastUpdated: "2026-08-07",
    },
  }),
  skill({
    id: "docker",
    slug: "docker",
    name: "Docker",
    domainId: "devops",
    x: 720,
    y: 480,
    summary: "Container packaging for reproducible ML and AI deployments.",
    what: "Platform for building, shipping, and running applications in containers.",
    why: "Eliminates 'works on my machine' — essential for ML model serving and CI/CD.",
    usedIn: ["ML serving", "CI/CD pipelines", "Local dev environments", "Batch training jobs"],
    requiredByRoles: ["mlops-engineer", "ai-engineer", "fde-engineer"],
    learnTopics: ["Images", "Dockerfile", "Multi-stage builds", "Compose", "Registry", "Volumes", "Networking"],
    buildProject: "Containerize a FastAPI ML service with optimized image layers.",
    productionReality: ["Large images slowing deploys", "Wrong base image", "Secret leakage in layers", "Volume permission issues"],
    interviewPoints: ["Image layering and cache optimization", "Multi-stage builds for Python ML apps", "Container security basics"],
    connectedSkills: ["kubernetes", "linux", "cicd"],
    prerequisites: ["linux"],
    alternatives: ["Podman", "containerd"],
    maturity: "L3",
    modes: {
      roadmap: "First container skill — learn before Kubernetes.",
      architecture: "Packages models, APIs, and workers into portable units.",
      company: "Near-universal expectation for backend and platform-oriented roles.",
      projects: "Dockerize every API and training job you build.",
      interview: "Explain images, layers, and production Dockerfile best practices.",
      career: "Foundation for all production AI engineering paths.",
    },
  }),
  skill({
    id: "python",
    slug: "python",
    name: "Python",
    domainId: "software",
    x: 480,
    y: 240,
    summary: "Primary language for ML, LLM apps, automation, and data engineering.",
    what: "General-purpose language dominant in AI/ML ecosystems.",
    why: "Libraries for ML, LLMs, data, and automation all converge on Python.",
    usedIn: ["ML training", "FastAPI services", "LangChain agents", "Data pipelines", "MLOps scripts"],
    requiredByRoles: ["ai-engineer", "mlops-engineer", "llmops-engineer", "ai-ml-engineer"],
    learnTopics: ["Typing", "Async", "Virtual envs", "Packaging", "Testing", "Profiling"],
    buildProject: "Production FastAPI service with structured logging and tests.",
    productionReality: ["Memory leaks", "GIL limitations", "Dependency conflicts", "Slow cold starts"],
    interviewPoints: ["Async vs sync for I/O-bound ML APIs", "How do you structure a production Python service?"],
    connectedSkills: ["fastapi", "pytorch", "langchain"],
    prerequisites: [],
    alternatives: ["Go", "Java", "TypeScript"],
    maturity: "L3",
    modes: {
      roadmap: "Start here for almost every AI engineering path.",
      architecture: "Implements APIs, pipelines, agents, and glue code.",
      company: "Required in the vast majority of AI/ML job descriptions analyzed.",
      projects: "Build every capstone in Python first.",
      interview: "Expect clean code, testing, and API design questions.",
      career: "Non-negotiable for ML, MLOps, LLMOps, and GenAI roles.",
    },
  }),
  skill({
    id: "mlflow",
    slug: "mlflow",
    name: "MLflow",
    domainId: "mlops",
    x: 200,
    y: 480,
    summary: "Experiment tracking, model registry, and ML lifecycle management.",
    what: "Open-source platform for the ML lifecycle: experiments, registry, deployment.",
    why: "Brings reproducibility and governance to model development in teams.",
    usedIn: ["Experiment tracking", "Model registry", "ML pipelines", "Model deployment"],
    requiredByRoles: ["mlops-engineer", "ai-ml-engineer"],
    learnTopics: ["Tracking API", "Model registry", "Projects", "Artifacts", "Model serving"],
    buildProject: "End-to-end pipeline with tracked experiments and registered models.",
    productionReality: ["Artifact storage costs", "Registry permission models", "Version conflicts"],
    interviewPoints: ["How does MLflow improve reproducibility?", "Registry vs experiment tracking"],
    connectedSkills: ["kubernetes", "python", "kubeflow"],
    prerequisites: ["python", "docker"],
    alternatives: ["Weights & Biases", "Neptune", "Kubeflow"],
    maturity: "L2",
    modes: {
      roadmap: "Learn after Python and basic ML training workflows.",
      architecture: "Central experiment and model metadata layer in MLOps stacks.",
      company: "Common in MLOps-oriented postings; often paired with Kubernetes.",
      projects: "Track every experiment in your capstone pipeline.",
      interview: "Explain experiment reproducibility and model promotion workflows.",
      career: "Core MLOps differentiator from pure ML engineering.",
    },
  }),
  skill({
    id: "rag",
    slug: "rag",
    name: "RAG",
    domainId: "rag",
    x: 360,
    y: 220,
    summary: "Retrieval-augmented generation for enterprise knowledge applications.",
    what: "Pattern combining retrieval from a knowledge base with LLM generation.",
    why: "Grounds LLM responses in private data without full fine-tuning.",
    usedIn: ["Document Q&A", "Support bots", "Enterprise search", "Compliance-aware assistants"],
    requiredByRoles: ["llmops-engineer", "ai-engineer", "fde-engineer"],
    learnTopics: ["Chunking", "Embeddings", "Vector search", "Reranking", "Citation", "Evaluation"],
    buildProject: "Production RAG system with evaluation harness and citation tracking.",
    productionReality: ["Bad chunking", "Stale indexes", "Hallucination despite RAG", "Latency spikes", "Cost blowups"],
    interviewPoints: ["RAG vs fine-tuning tradeoffs", "How do you evaluate RAG quality?", "Chunking strategies"],
    connectedSkills: ["vector-databases", "langchain", "llms"],
    prerequisites: ["python", "llms"],
    alternatives: ["Fine-tuning", "Knowledge graphs"],
    maturity: "L2",
    modes: {
      roadmap: "Learn after LLM fundamentals and Python APIs.",
      architecture: "Sits between ingestion, vector DB, reranker, and LLM in GenAI systems.",
      company: "Among the most requested GenAI capabilities in analyzed postings.",
      projects: "Build enterprise doc Q&A with eval metrics.",
      interview: "Expect architecture, evaluation, and failure mode depth.",
      career: "Central to LLMOps and GenAI engineer paths.",
    },
  }),
  skill({
    id: "vector-databases",
    slug: "vector-databases",
    name: "Vector Databases",
    domainId: "rag",
    x: 320,
    y: 280,
    summary: "Stores and queries embeddings for semantic search and RAG.",
    what: "Databases optimized for similarity search over high-dimensional vectors.",
    why: "Enables fast retrieval for RAG, recommendations, and semantic search.",
    usedIn: ["RAG pipelines", "Semantic search", "Recommendation systems"],
    requiredByRoles: ["llmops-engineer", "ai-engineer"],
    learnTopics: ["ChromaDB", "Pinecone", "Weaviate", "pgvector", "Indexing strategies", "Hybrid search"],
    buildProject: "Vector index with hybrid keyword + semantic search.",
    productionReality: ["Index rebuild times", "Recall vs latency tradeoffs", "Embedding model changes invalidating indexes"],
    interviewPoints: ["When to use vector DB vs traditional search?", "Hybrid retrieval strategies"],
    connectedSkills: ["rag", "embeddings", "langchain"],
    prerequisites: ["rag"],
    alternatives: ["Elasticsearch kNN", "OpenSearch"],
    maturity: "L2",
    modes: {
      roadmap: "Learn alongside or immediately after RAG fundamentals.",
      architecture: "Persistence layer between embeddings and retrieval API.",
      company: "Common in GenAI and LLMOps job descriptions.",
      projects: "Integrate ChromaDB or pgvector in a RAG capstone.",
      interview: "Indexing, recall, and operational concerns.",
      career: "Required for production LLM applications.",
    },
  }),
  skill({
    id: "langchain",
    slug: "langchain",
    name: "LangChain",
    domainId: "agents",
    x: 440,
    y: 760,
    summary: "Framework for LLM applications, chains, and agent orchestration.",
    what: "Framework for building LLM-powered applications with chains, tools, and memory.",
    why: "Accelerates agent and RAG development with composable abstractions.",
    usedIn: ["RAG apps", "Agents", "Tool-calling workflows", "Multi-step reasoning"],
    requiredByRoles: ["ai-engineer", "llmops-engineer", "fde-engineer"],
    learnTopics: ["Chains", "Agents", "Tools", "Memory", "LangGraph", "Evaluators"],
    buildProject: "Multi-tool agent with observability and error handling.",
    productionReality: ["Abstraction leaks", "Debugging complexity", "Version churn", "Latency from chain depth"],
    interviewPoints: ["LangChain vs raw API approach", "Agent design patterns", "LangGraph for stateful flows"],
    connectedSkills: ["rag", "mcp", "llms"],
    prerequisites: ["python", "llms"],
    alternatives: ["LlamaIndex", "Haystack", "Raw API + custom orchestration"],
    maturity: "L2",
    modes: {
      roadmap: "Learn after RAG and LLM API fundamentals.",
      architecture: "Orchestration layer for agents, tools, and retrieval.",
      company: "Frequently listed in GenAI and agent engineering postings.",
      projects: "Build agent with tool use and human-in-the-loop.",
      interview: "Agent patterns, tool selection, and production concerns.",
      career: "Key skill for Agentic AI and LLMOps paths.",
    },
  }),
  skill({
    id: "mcp",
    slug: "mcp",
    name: "MCP",
    domainId: "agents",
    x: 400,
    y: 800,
    summary: "Model Context Protocol for connecting agents to enterprise tools and data.",
    what: "Open protocol for AI applications to connect to external tools, data, and prompts.",
    why: "Standardizes agent integrations with GitHub, databases, K8s, and internal systems.",
    usedIn: ["Enterprise agents", "IDE assistants", "DevOps automation", "Support workflows"],
    requiredByRoles: ["ai-engineer", "fde-engineer", "llmops-engineer"],
    learnTopics: ["MCP servers", "Resources", "Tools", "Prompts", "Auth boundaries", "Security"],
    buildProject: "MCP server connecting an agent to GitHub and Kubernetes.",
    productionReality: ["Auth scope creep", "Tool permission boundaries", "Latency from tool chains"],
    interviewPoints: ["MCP vs direct API integration", "Security boundaries for enterprise agents"],
    connectedSkills: ["langchain", "agents", "security"],
    prerequisites: ["langchain", "python"],
    alternatives: ["Direct API integrations", "A2A protocol"],
    maturity: "L1",
    modes: {
      roadmap: "Learn after basic agents and tool use — emerging but high demand.",
      architecture: "Standard integration layer between agents and enterprise systems.",
      company: "Rapidly growing mention in agent and automation postings (2026).",
      projects: "Build MCP server for a real internal workflow.",
      interview: "Explain MCP resources vs tools vs prompts.",
      career: "Differentiator for FDE and Agentic AI roles.",
    },
  }),
  skill({
    id: "llms",
    slug: "llms",
    name: "LLMs",
    domainId: "genai",
    x: 240,
    y: 300,
    summary: "Large language models — APIs, prompting, fine-tuning, and evaluation.",
    what: "Large language models accessed via API or self-hosted for text generation and reasoning.",
    why: "Foundation of modern GenAI, RAG, agents, and LLMOps systems.",
    usedIn: ["Chatbots", "RAG", "Agents", "Code generation", "Summarization"],
    requiredByRoles: ["ai-engineer", "llmops-engineer", "llmops-engineer"],
    learnTopics: ["Prompting", "Token economics", "Fine-tuning", "Evaluation", "Guardrails", "Routing"],
    buildProject: "LLM application with evaluation harness and cost monitoring.",
    productionReality: ["Hallucinations", "Rate limits", "Cost spikes", "Latency", "Provider outages"],
    interviewPoints: ["Prompt vs fine-tune vs RAG", "Evaluation strategies", "Cost optimization"],
    connectedSkills: ["rag", "langchain", "vllm"],
    prerequisites: ["python"],
    alternatives: ["Open-source models", "Smaller specialized models"],
    maturity: "L2",
    modes: {
      roadmap: "Core after Python for GenAI, LLMOps, and agent paths.",
      architecture: "Central inference component in GenAI system design.",
      company: "Universal expectation in GenAI and LLMOps roles.",
      projects: "Every GenAI capstone involves LLM integration.",
      interview: "Deep on evaluation, cost, and production failure modes.",
      career: "Required for LLMOps, GenAI, and Agentic AI careers.",
    },
  }),
  skill({
    id: "vllm",
    slug: "vllm",
    name: "vLLM",
    domainId: "infra",
    x: 260,
    y: 540,
    summary: "High-throughput LLM inference serving with PagedAttention.",
    what: "Inference engine optimized for serving LLMs with high throughput and low latency.",
    why: "Production LLM serving requires specialized runtimes beyond raw API calls.",
    usedIn: ["Self-hosted LLM inference", "GPU clusters", "AI gateways"],
    requiredByRoles: ["ai-infrastructure-engineer", "llmops-engineer"],
    learnTopics: ["PagedAttention", "Batching", "KV cache", "GPU utilization", "OpenAI-compatible API"],
    buildProject: "Self-hosted LLM endpoint with autoscaling on GPU nodes.",
    productionReality: ["GPU OOM", "KV cache exhaustion", "Cold start latency", "Model loading time"],
    interviewPoints: ["How does vLLM improve throughput?", "GPU memory management for inference"],
    connectedSkills: ["kubernetes", "gpu", "llms"],
    prerequisites: ["kubernetes", "llms", "docker"],
    alternatives: ["Triton", "TensorRT-LLM", "Ollama"],
    maturity: "L2",
    modes: {
      roadmap: "Advanced — after Kubernetes and LLM fundamentals.",
      architecture: "Inference runtime behind API gateway on GPU infrastructure.",
      company: "Specialized skill for AI infrastructure and senior LLMOps roles.",
      projects: "Deploy vLLM on K8s with monitoring.",
      interview: "Inference optimization and GPU troubleshooting.",
      career: "Key for AI Infrastructure Engineer path.",
    },
  }),
  skill({
    id: "gpu",
    slug: "gpu",
    name: "GPU Infrastructure",
    domainId: "infra",
    x: 220,
    y: 620,
    summary: "GPU scheduling, memory, and compute for AI training and inference.",
    what: "Graphics processing units used for parallel ML training and LLM inference.",
    why: "AI workloads are compute-bound — GPU infrastructure is the bottleneck at scale.",
    usedIn: ["Model training", "LLM inference", "Embedding generation", "Fine-tuning"],
    requiredByRoles: ["ai-infrastructure-engineer", "mlops-engineer"],
    learnTopics: ["NVIDIA GPUs", "CUDA basics", "MIG", "GPU Operator", "Scheduling", "NCCL"],
    buildProject: "GPU-enabled training job with monitoring and cost tracking.",
    productionReality: ["GPU fragmentation", "OOM", "Driver mismatches", "Spot instance preemption"],
    interviewPoints: ["GPU scheduling on Kubernetes", "Training vs inference GPU needs"],
    connectedSkills: ["kubernetes", "vllm", "pytorch"],
    prerequisites: ["kubernetes", "linux"],
    alternatives: ["TPU", "AWS Inferentia"],
    maturity: "L2",
    modes: {
      roadmap: "Advanced path — AI Infrastructure and senior MLOps.",
      architecture: "Compute layer under training and inference pipelines.",
      company: "Expected for AI infrastructure roles; growing in LLMOps.",
      projects: "Run distributed training or vLLM on GPU nodes.",
      interview: "GPU memory, scheduling, and cost optimization.",
      career: "Defines AI Infrastructure Engineer specialization.",
    },
  }),
  skill({
    id: "terraform",
    slug: "terraform",
    name: "Terraform",
    domainId: "cloud",
    x: 700,
    y: 280,
    summary: "Infrastructure as code for reproducible cloud and AI platforms.",
    what: "IaC tool for defining and provisioning cloud infrastructure declaratively.",
    why: "Reproducible environments for ML platforms, GPU clusters, and data infra.",
    usedIn: ["Cloud provisioning", "K8s cluster setup", "Networking", "IAM"],
    requiredByRoles: ["mlops-engineer", "ai-infrastructure-engineer", "platform-engineer"],
    learnTopics: ["HCL", "State", "Modules", "Workspaces", "IAM", "Remote state"],
    buildProject: "Terraform module for a GPU-enabled EKS/GKE cluster.",
    productionReality: ["State drift", "Blast radius of changes", "Secret management in state"],
    interviewPoints: ["IaC best practices", "Managing Terraform state in teams"],
    connectedSkills: ["kubernetes", "aws", "cicd"],
    prerequisites: ["cloud"],
    alternatives: ["Pulumi", "CloudFormation", "Crossplane"],
    maturity: "L2",
    modes: {
      roadmap: "Learn after cloud basics, parallel with Kubernetes.",
      architecture: "Provisions the infrastructure layer everything runs on.",
      company: "Standard for platform, DevOps, and MLOps roles.",
      projects: "IaC for every cloud resource in capstones.",
      interview: "State management, modules, and safe change practices.",
      career: "Bridge from Cloud/DevOps into MLOps and AI infra.",
    },
  }),
  skill({
    id: "prometheus",
    slug: "prometheus",
    name: "Prometheus",
    domainId: "observability",
    x: 520,
    y: 360,
    summary: "Metrics collection and alerting for ML and AI systems.",
    what: "Open-source monitoring system with time-series metrics and PromQL.",
    why: "Observability is non-negotiable for production ML, LLM, and agent systems.",
    usedIn: ["ML model monitoring", "API latency tracking", "GPU metrics", "AIOps anomaly detection"],
    requiredByRoles: ["mlops-engineer", "aiops-engineer", "ai-infrastructure-engineer"],
    learnTopics: ["Metrics", "PromQL", "Alertmanager", "ServiceMonitor", "Grafana integration"],
    buildProject: "Monitoring dashboard for ML API with drift and latency alerts.",
    productionReality: ["Cardinality explosion", "Alert fatigue", "Missing golden signals"],
    interviewPoints: ["What metrics matter for ML inference?", "SLO-based alerting"],
    connectedSkills: ["grafana", "kubernetes", "aiops"],
    prerequisites: ["kubernetes"],
    alternatives: ["Datadog", "CloudWatch", "VictoriaMetrics"],
    maturity: "L2",
    modes: {
      roadmap: "Learn with or after Kubernetes for production paths.",
      architecture: "Metrics layer in observability stack for AI systems.",
      company: "Common in SRE, MLOps, and AIOps postings.",
      projects: "Add metrics to every deployed service.",
      interview: "Golden signals and ML-specific monitoring.",
      career: "Required for MLOps, AIOps, and AI infrastructure.",
    },
  }),
  skill({
    id: "kserve",
    slug: "kserve",
    name: "KServe",
    domainId: "mlops",
    x: 180,
    y: 520,
    summary: "Kubernetes-native model serving with autoscaling and canary deployments.",
    what: "Kubernetes CRD-based model serving framework built on Knative.",
    why: "Standardizes model deployment on K8s with scale-to-zero and traffic splitting.",
    usedIn: ["ML model serving", "Inference autoscaling", "Canary model rollouts"],
    requiredByRoles: ["mlops-engineer", "ai-infrastructure-engineer"],
    learnTopics: ["InferenceService", "Predictor", "Transformer", "Canary", "GPU serving"],
    buildProject: "Deploy sklearn and ONNX models with KServe on Kubernetes.",
    productionReality: ["Cold start latency", "Knative complexity", "Custom runtime debugging"],
    interviewPoints: ["KServe vs raw Deployment for models", "Canary deployment strategies"],
    connectedSkills: ["kubernetes", "mlflow", "docker"],
    prerequisites: ["kubernetes", "docker"],
    alternatives: ["Seldon Core", "BentoML", "SageMaker Endpoints"],
    maturity: "L3",
    modes: {
      roadmap: "Advanced MLOps — after Kubernetes and MLflow.",
      architecture: "Model serving layer on Kubernetes in enterprise MLOps stacks.",
      company: "Seen in Kubernetes-heavy MLOps and platform roles.",
      projects: "Serve models from your MLflow registry via KServe.",
      interview: "Model serving patterns and autoscaling on K8s.",
      career: "Senior MLOps and AI infrastructure differentiator.",
    },
  }),
  skill({
    id: "linux",
    slug: "linux",
    name: "Linux",
    domainId: "software",
    x: 460,
    y: 200,
    summary: "Operating system fundamentals for all infrastructure and AI engineering.",
    what: "Unix-like OS powering servers, containers, and cloud infrastructure.",
    why: "Every production system runs on Linux — debugging starts here.",
    usedIn: ["Servers", "Containers", "CI runners", "GPU nodes"],
    requiredByRoles: ["mlops-engineer", "ai-infrastructure-engineer", "fde-engineer"],
    learnTopics: ["Shell", "Processes", "Networking", "Filesystem", "systemd", "Permissions"],
    buildProject: "Debug a production incident using only shell tools.",
    productionReality: ["Disk full", "Permission denied", "Zombie processes", "Network timeouts"],
    interviewPoints: ["Debug high CPU", "Explain file descriptors and limits"],
    connectedSkills: ["docker", "kubernetes"],
    prerequisites: [],
    alternatives: [],
    maturity: "L3",
    modes: {
      roadmap: "Start here — before Docker and cloud.",
      architecture: "Foundation OS for all deployed workloads.",
      company: "Universal baseline for infrastructure roles.",
      projects: "Comfort on CLI for every deployment task.",
      interview: "Troubleshooting and systems fundamentals.",
      career: "Non-negotiable foundation skill.",
    },
  }),
  skill({
    id: "cicd",
    slug: "cicd",
    name: "CI/CD",
    domainId: "devops",
    x: 800,
    y: 520,
    summary: "Automated build, test, and deploy pipelines for ML and software.",
    what: "Continuous integration and delivery pipelines automating software releases.",
    why: "ML models and AI services need automated, repeatable deployment.",
    usedIn: ["Model training pipelines", "API deployments", "Infrastructure changes"],
    requiredByRoles: ["mlops-engineer", "devops-engineer"],
    learnTopics: ["GitHub Actions", "Jenkins", "ArgoCD", "GitOps", "Pipeline design"],
    buildProject: "CI/CD pipeline that trains, validates, and deploys a model.",
    productionReality: ["Flaky tests blocking deploys", "Secret management", "Pipeline drift"],
    interviewPoints: ["CI/CD for ML vs traditional software", "GitOps patterns"],
    connectedSkills: ["docker", "kubernetes", "terraform", "git"],
    prerequisites: ["git", "docker"],
    alternatives: ["GitLab CI", "CircleCI"],
    maturity: "L2",
    modes: {
      roadmap: "Learn after Git and Docker.",
      architecture: "Automation layer connecting code to production.",
      company: "Expected in DevOps, MLOps, and platform roles.",
      projects: "Automate every capstone deployment.",
      interview: "Pipeline design and ML-specific CI/CD.",
      career: "Core DevOps → MLOps bridge skill.",
    },
  }),
  skill({
    id: "git",
    slug: "git",
    name: "Git",
    domainId: "software",
    x: 440,
    y: 180,
    summary: "Version control for code, configs, and ML artifacts — required in every engineering role.",
    what: "Distributed version control system for tracking code and collaborating in teams.",
    why: "Every pipeline, model repo, and infrastructure change starts with Git. No Git means no CI/CD.",
    usedIn: ["Application code", "IaC repos", "ML notebooks", "GitOps deployments", "Team collaboration"],
    requiredByRoles: ["devops-engineer", "mlops-engineer", "ai-engineer", "fde-engineer"],
    learnTopics: ["Commits & branches", "Pull requests", "Merge/rebase", "GitHub/GitLab", ".gitignore", "Tags & releases"],
    buildProject: "Contribute to a team repo with feature branches, PR reviews, and protected main.",
    productionReality: ["Merge conflicts", "Force-push accidents", "Large file commits", "Leaked secrets in history"],
    interviewPoints: ["Explain branching strategies (GitFlow, trunk-based)", "How do you recover from a bad merge?", "GitOps vs traditional deploy"],
    connectedSkills: ["cicd", "python", "terraform"],
    prerequisites: [],
    alternatives: ["Mercurial"],
    maturity: "L2",
    modes: {
      roadmap: "Learn before CI/CD — every other tool assumes you know Git.",
      architecture: "Source of truth for application, infra, and pipeline definitions.",
      company: "Universal requirement across all software and platform job postings.",
      projects: "Put every capstone in a Git repo from day one.",
      interview: "Branching, collaboration workflows, and incident recovery.",
      career: "Non-negotiable baseline — skipped only at your own risk.",
    },
  }),
  skill({
    id: "sql",
    slug: "sql",
    name: "SQL",
    domainId: "data",
    x: 560,
    y: 760,
    summary: "Query and model structured data — features, metrics, and app state all live here.",
    what: "Structured query language for relational databases and warehouses.",
    why: "Training data, feature stores, user data, and business metrics are overwhelmingly SQL-backed.",
    usedIn: ["Feature engineering", "Data pipelines", "Analytics", "App backends", "RAG metadata stores"],
    requiredByRoles: ["ai-engineer", "mlops-engineer", "fde-engineer"],
    learnTopics: ["SELECT/JOIN", "Aggregations", "Indexes", "PostgreSQL", "Query optimization", "Migrations"],
    buildProject: "Build a feature pipeline that reads from PostgreSQL and writes engineered features for ML.",
    productionReality: ["Slow queries", "Missing indexes", "Lock contention", "Schema drift", "N+1 query patterns"],
    interviewPoints: ["Explain JOIN types with examples", "How would you optimize a slow analytics query?", "SQL vs NoSQL for ML features"],
    connectedSkills: ["python", "mlflow"],
    prerequisites: [],
    alternatives: ["NoSQL", "Spark SQL"],
    maturity: "L2",
    modes: {
      roadmap: "Learn alongside Python — most real AI systems touch a database.",
      architecture: "Persistence layer for features, users, eval results, and audit logs.",
      company: "Frequently listed for ML, data, and full-stack AI engineer roles.",
      projects: "Back every API and pipeline with a real database schema.",
      interview: "Query writing, optimization, and data modeling basics.",
      career: "Expected even for infra-heavy roles when debugging data issues.",
    },
  }),
  skill({
    id: "cloud",
    slug: "cloud",
    name: "Cloud (AWS / GCP / Azure)",
    domainId: "cloud",
    x: 700,
    y: 280,
    summary: "Managed compute, storage, and AI services — where production workloads actually run.",
    what: "Public cloud platforms providing VMs, Kubernetes, object storage, and managed ML/AI APIs.",
    why: "Job postings expect at least one cloud. MLOps, LLMOps, and FDE roles deploy on AWS, GCP, or Azure daily.",
    usedIn: ["EKS/GKE/AKS", "S3/GCS/Blob storage", "IAM & networking", "Bedrock/Vertex/Azure OpenAI", "GPU instances"],
    requiredByRoles: ["mlops-engineer", "llmops-engineer", "devops-engineer", "fde-engineer", "ai-infrastructure-engineer"],
    learnTopics: ["IAM", "VPC/VNet", "Object storage", "Managed Kubernetes", "CloudWatch/Cloud Monitoring", "Cost tags"],
    buildProject: "Deploy a containerized ML API on managed Kubernetes with object storage for artifacts.",
    productionReality: ["IAM misconfiguration", "Runaway bills", "Quota limits", "Region outages", "Over-permissive roles"],
    interviewPoints: ["Design a secure VPC for an ML workload", "How do you control cloud costs for GPU training?", "Compare managed K8s offerings"],
    connectedSkills: ["kubernetes", "terraform", "docker", "cicd"],
    prerequisites: ["linux"],
    alternatives: ["On-prem only (rare in hiring)"],
    maturity: "L2",
    modes: {
      roadmap: "Learn after Linux and alongside Terraform — most teams hire for AWS or GCP.",
      architecture: "Hosts clusters, storage, managed AI APIs, and networking for the full stack.",
      company: "Listed in the vast majority of MLOps, platform, and AI infra job descriptions.",
      projects: "Run at least one capstone entirely in a cloud account.",
      interview: "IAM, networking, managed services, and cost awareness.",
      career: "Bridge from local Docker skills to production deployments.",
    },
    companyDemand: {
      level: "high",
      sampleNote: "AWS, GCP, or Azure appears in most analyzed production AI and platform postings.",
      roles: ["MLOps Engineer", "LLMOps Engineer", "Platform Engineer", "FDE"],
      lastUpdated: "2026-08-07",
    },
  }),
  skill({
    id: "helm",
    slug: "helm",
    name: "Helm",
    domainId: "devops",
    x: 820,
    y: 360,
    summary: "Package and release Kubernetes apps — standard for MLOps and platform teams.",
    what: "Package manager for Kubernetes that templates and versions cluster deployments.",
    why: "Raw YAML does not scale. Helm charts are how teams ship KServe, MLflow, and internal platforms.",
    usedIn: ["ML platform installs", "KServe deployments", "GitOps releases", "Environment promotion"],
    requiredByRoles: ["mlops-engineer", "ai-infrastructure-engineer", "devops-engineer"],
    learnTopics: ["Charts & templates", "values.yaml", "Helm releases", "Hooks", "Chart repos", "Upgrades & rollbacks"],
    buildProject: "Package your inference service as a Helm chart with dev/staging/prod values.",
    productionReality: ["Failed upgrades", "Template sprawl", "Secret handling in charts", "Version skew across envs"],
    interviewPoints: ["Helm vs Kustomize", "How do you promote a chart from staging to prod?", "Templating best practices"],
    connectedSkills: ["kubernetes", "cicd", "kserve"],
    prerequisites: ["kubernetes"],
    alternatives: ["Kustomize", "Raw manifests"],
    maturity: "L2",
    modes: {
      roadmap: "Learn right after Kubernetes — required for real MLOps platform work.",
      architecture: "Packaging layer between CI/CD and running cluster workloads.",
      company: "Common in MLOps and platform engineering postings alongside Kubernetes.",
      projects: "Never deploy to K8s without a chart or equivalent.",
      interview: "Chart structure, upgrades, and environment management.",
      career: "Separates hobby K8s from production platform engineering.",
    },
  }),
  skill({
    id: "grafana",
    slug: "grafana",
    name: "Grafana",
    domainId: "observability",
    x: 560,
    y: 340,
    summary: "Dashboards and alerting on top of Prometheus — how teams actually see production health.",
    what: "Observability platform for metrics visualization, dashboards, and alerting.",
    why: "Prometheus collects metrics; Grafana is what on-call engineers stare at. Job posts list both together.",
    usedIn: ["SLO dashboards", "ML inference monitoring", "GPU utilization views", "Incident response", "Cost dashboards"],
    requiredByRoles: ["mlops-engineer", "llmops-engineer", "ai-infrastructure-engineer", "devops-engineer"],
    learnTopics: ["Dashboards", "PromQL queries", "Alert rules", "Data sources", "Annotations", "On-call workflows"],
    buildProject: "Grafana dashboard for an ML API: latency, error rate, GPU memory, and model version.",
    productionReality: ["Alert fatigue", "Missing labels", "Dashboard sprawl", "Stale panels", "False positives"],
    interviewPoints: ["What metrics matter for ML inference?", "How do you design actionable alerts?", "SLO-based alerting"],
    connectedSkills: ["prometheus", "kubernetes"],
    prerequisites: ["prometheus"],
    alternatives: ["Datadog", "New Relic", "Cloud-native consoles"],
    maturity: "L2",
    modes: {
      roadmap: "Learn immediately after Prometheus — they are a pair in production.",
      architecture: "Visualization and alerting layer on metrics, logs, and traces.",
      company: "Prometheus/Grafana stack appears frequently in SRE, MLOps, and platform roles.",
      projects: "Every deployed service gets a dashboard before it goes live.",
      interview: "Metrics selection, SLOs, and on-call practices.",
      career: "Required for anyone owning production reliability.",
    },
  }),
  skill({
    id: "fastapi",
    slug: "fastapi",
    name: "FastAPI",
    domainId: "software",
    x: 500,
    y: 300,
    summary: "Production Python APIs for ML inference, RAG endpoints, and agent backends.",
    what: "Modern async Python web framework for building high-performance APIs.",
    why: "AI Engineer and LLMOps roles expect you to ship REST APIs around models — FastAPI is the default.",
    usedIn: ["ML inference APIs", "RAG endpoints", "Agent tool servers", "Webhooks", "Internal microservices"],
    requiredByRoles: ["ai-engineer", "llmops-engineer", "fde-engineer", "mlops-engineer"],
    learnTopics: ["Routes & dependencies", "Pydantic models", "Async I/O", "OpenAPI docs", "Middleware", "Testing"],
    buildProject: "FastAPI service wrapping an LLM with structured outputs, health checks, and request logging.",
    productionReality: ["Blocking calls in async routes", "Memory growth under load", "Auth gaps", "Cold start latency"],
    interviewPoints: ["Why FastAPI for ML services?", "Sync vs async for inference endpoints", "API design for agents"],
    connectedSkills: ["python", "docker", "kubernetes", "llms"],
    prerequisites: ["python"],
    alternatives: ["Flask", "Django REST", "gRPC"],
    maturity: "L2",
    modes: {
      roadmap: "Learn after Python — before shipping any model or RAG feature.",
      architecture: "HTTP layer in front of models, retrievers, and agent orchestrators.",
      company: "Very common in AI engineer and GenAI application postings.",
      projects: "Expose every model and agent as a documented API.",
      interview: "API design, async patterns, and production hardening.",
      career: "Turns notebook code into something a team can deploy.",
    },
  }),
  skill({
    id: "pytorch",
    slug: "pytorch",
    name: "PyTorch",
    domainId: "ml",
    x: 320,
    y: 720,
    summary: "Train and fine-tune models — the ML foundation behind MLOps and many LLM workflows.",
    what: "Deep learning framework for building, training, and exporting neural network models.",
    why: "MLOps engineers need to understand training loops, checkpoints, and exports — not just pipelines around models others built.",
    usedIn: ["Model training", "Fine-tuning", "Research prototypes", "ONNX export", "Custom layers"],
    requiredByRoles: ["mlops-engineer", "ai-ml-engineer", "llmops-engineer"],
    learnTopics: ["Tensors", "Autograd", "Training loops", "DataLoader", "GPU training", "HuggingFace integration"],
    buildProject: "Train a classifier, track metrics, export to ONNX, and serve via an API.",
    productionReality: ["OOM during training", "Non-determinism", "Checkpoint corruption", "Train/serve skew"],
    interviewPoints: ["Explain training vs inference graph", "How do you debug NaN losses?", "Fine-tuning vs training from scratch"],
    connectedSkills: ["python", "mlflow", "gpu"],
    prerequisites: ["python"],
    alternatives: ["TensorFlow", "JAX"],
    maturity: "L2",
    modes: {
      roadmap: "Learn after Python — before MLflow and model serving make sense.",
      architecture: "Training layer that feeds experiment tracking and deployment pipelines.",
      company: "Expected for ML engineer and MLOps roles; useful for LLMOps fine-tuning work.",
      projects: "Train at least one model end-to-end before automating the pipeline.",
      interview: "Training fundamentals, not just tool names.",
      career: "Credibility with ML teams — you understand what the pipeline is shipping.",
    },
  }),
];

export const RELATIONS: Relation[] = [
  { from: "kubernetes", to: "docker", type: "requires" },
  { from: "kubernetes", to: "linux", type: "requires" },
  { from: "docker", to: "linux", type: "requires" },
  { from: "cicd", to: "git", type: "requires" },
  { from: "cicd", to: "docker", type: "requires" },
  { from: "mlflow", to: "python", type: "requires" },
  { from: "mlflow", to: "pytorch", type: "builds_on" },
  { from: "fastapi", to: "python", type: "requires" },
  { from: "pytorch", to: "python", type: "requires" },
  { from: "helm", to: "kubernetes", type: "requires" },
  { from: "grafana", to: "prometheus", type: "builds_on" },
  { from: "terraform", to: "cloud", type: "builds_on" },
  { from: "kubernetes", to: "cloud", type: "deployed_on" },
  { from: "rag", to: "llms", type: "builds_on" },
  { from: "vector-databases", to: "rag", type: "part_of" },
  { from: "langchain", to: "llms", type: "builds_on" },
  { from: "mcp", to: "langchain", type: "builds_on" },
  { from: "vllm", to: "kubernetes", type: "deployed_on" as Relation["type"] },
  { from: "kserve", to: "kubernetes", type: "deployed_on" as Relation["type"] },
  { from: "kserve", to: "helm", type: "builds_on" },
  { from: "prometheus", to: "kubernetes", type: "monitored_by" as Relation["type"] },
  { from: "terraform", to: "kubernetes", type: "builds_on" },
  { from: "gpu", to: "kubernetes", type: "part_of" },
  { from: "sql", to: "python", type: "used_by" as Relation["type"] },
];

export const ROLES: RoleProfile[] = [
  {
    id: "devops-engineer",
    slug: "devops-engineer",
    name: "DevOps Engineer",
    description: "CI/CD, containers, infrastructure automation, and release engineering.",
    salaryIndia: "₹10–35 LPA",
    dna: [
      { label: "Linux", score: 9 },
      { label: "DevOps", score: 10 },
      { label: "Cloud", score: 8 },
      { label: "Kubernetes", score: 8 },
      { label: "ML", score: 2 },
      { label: "LLMs", score: 1 },
    ],
    core: ["Linux", "Docker", "Kubernetes", "CI/CD", "Terraform", "Cloud"],
    important: ["Prometheus", "GitOps", "Security", "Networking"],
    advanced: ["Platform engineering", "Service mesh", "Policy as code"],
    skillIds: ["linux", "git", "docker", "kubernetes", "terraform", "cicd", "prometheus", "grafana", "cloud", "helm"],
    responsibilities: ["CI/CD pipelines", "Infrastructure automation", "Release management", "Incident response"],
  },
  {
    id: "mlops-engineer",
    slug: "mlops-engineer",
    name: "MLOps Engineer",
    description: "Owns the ML lifecycle from experiment to production deployment and monitoring.",
    salaryIndia: "₹12–40 LPA",
    roadmapSlug: "mlops-engineer",
    dna: [
      { label: "Software Engineering", score: 7 },
      { label: "DevOps", score: 9 },
      { label: "Cloud", score: 8 },
      { label: "Kubernetes", score: 9 },
      { label: "ML", score: 6 },
      { label: "Observability", score: 7 },
      { label: "LLMs", score: 4 },
    ],
    core: ["Python", "Docker", "Kubernetes", "CI/CD", "Cloud", "ML lifecycle"],
    important: ["Terraform", "MLflow", "Monitoring", "Data pipelines"],
    advanced: ["KServe", "Kubeflow", "Feature stores", "GPU workloads"],
    skillIds: ["linux", "git", "python", "sql", "docker", "kubernetes", "mlflow", "pytorch", "fastapi", "terraform", "prometheus", "grafana", "cicd", "cloud", "helm", "kserve"],
    responsibilities: ["ML pipelines", "Model deployment", "Monitoring & drift", "Infrastructure for ML"],
  },
  {
    id: "llmops-engineer",
    slug: "llmops-engineer",
    name: "LLMOps Engineer",
    description: "Operationalizes LLMs — RAG, evaluation, cost control, and production serving.",
    salaryIndia: "₹18–50 LPA",
    roadmapSlug: "llmops-engineer",
    dna: [
      { label: "Software Engineering", score: 7 },
      { label: "LLMs", score: 9 },
      { label: "RAG", score: 9 },
      { label: "Kubernetes", score: 7 },
      { label: "Observability", score: 7 },
      { label: "ML", score: 5 },
      { label: "Agents", score: 6 },
    ],
    core: ["Python", "LLM APIs", "RAG", "Vector DBs", "Evaluation", "Prompt management"],
    important: ["LangChain", "Kubernetes", "Cost monitoring", "Guardrails"],
    advanced: ["vLLM", "Fine-tuning", "Multi-model routing", "LLM gateways"],
    skillIds: ["linux", "git", "python", "fastapi", "llms", "rag", "vector-databases", "langchain", "kubernetes", "prometheus", "grafana", "cloud", "vllm"],
    responsibilities: ["RAG pipelines", "LLM evaluation", "Production serving", "Cost & latency optimization"],
  },
  {
    id: "ai-infrastructure-engineer",
    slug: "ai-infrastructure-engineer",
    name: "AI Infrastructure Engineer",
    description: "GPU clusters, inference runtimes, and compute infrastructure for AI at scale.",
    salaryIndia: "₹15–40 LPA",
    roadmapSlug: "ai-infrastructure-engineer",
    dna: [
      { label: "Linux", score: 9 },
      { label: "Kubernetes", score: 9 },
      { label: "GPU", score: 9 },
      { label: "Networking", score: 8 },
      { label: "Observability", score: 8 },
      { label: "ML", score: 4 },
      { label: "LLMs", score: 5 },
    ],
    core: ["Linux", "Kubernetes", "Terraform", "Networking", "GPU scheduling"],
    important: ["Prometheus", "vLLM", "Storage", "CI/CD"],
    advanced: ["CUDA", "NCCL", "Distributed training", "FinOps"],
    skillIds: ["linux", "git", "docker", "kubernetes", "terraform", "gpu", "vllm", "prometheus", "grafana", "cloud", "helm"],
    responsibilities: ["GPU infrastructure", "Inference serving", "Capacity planning", "Reliability & cost"],
  },
  {
    id: "fde-engineer",
    slug: "fde-engineer",
    name: "Forward Deployed Engineer",
    description: "Customer-facing AI delivery combining engineering, integration, and solution design.",
    salaryIndia: "₹18–45 LPA",
    roadmapSlug: "fde-engineer",
    dna: [
      { label: "Software", score: 8 },
      { label: "Cloud", score: 7 },
      { label: "AI/LLMs", score: 8 },
      { label: "Integration", score: 9 },
      { label: "Communication", score: 9 },
      { label: "DevOps", score: 6 },
    ],
    core: ["Python/TypeScript", "LLM APIs", "RAG", "Cloud", "API integration"],
    important: ["LangChain", "MCP", "Docker", "Customer communication"],
    advanced: ["Kubernetes", "Security", "Multi-agent systems"],
    skillIds: ["linux", "git", "python", "fastapi", "llms", "rag", "langchain", "mcp", "docker", "kubernetes", "cloud"],
    responsibilities: ["Rapid prototyping", "Customer integration", "Pilot deployments", "Solution architecture"],
  },
  {
    id: "ai-engineer",
    slug: "ai-engineer",
    name: "AI Engineer",
    description: "Builds LLM applications, agents, and production AI features.",
    salaryIndia: "₹15–50 LPA",
    roadmapSlug: "ai-engineer",
    dna: [
      { label: "Software", score: 8 },
      { label: "LLMs", score: 9 },
      { label: "RAG", score: 8 },
      { label: "Agents", score: 8 },
      { label: "Cloud", score: 6 },
      { label: "MLOps", score: 5 },
    ],
    core: ["Python", "LLM APIs", "RAG", "LangChain", "FastAPI"],
    important: ["Vector DBs", "Docker", "Evaluation", "MCP"],
    advanced: ["Multi-agent", "Fine-tuning", "Kubernetes"],
    skillIds: ["linux", "git", "python", "sql", "fastapi", "llms", "rag", "langchain", "vector-databases", "mcp", "docker"],
    responsibilities: ["LLM apps", "Agent systems", "RAG features", "API development"],
  },
];

export const FAILURE_SCENARIOS: FailureScenario[] = [
  {
    id: "k8s-oom",
    skillId: "kubernetes",
    title: "OOMKilled Pod",
    symptom: "Pod restarts repeatedly, status OOMKilled",
    evidence: ["kubectl describe pod shows OOMKilled", "Memory usage at limit in metrics", "Application logs cut off abruptly"],
    rootCause: "Container memory limit too low for workload (common with ML inference)",
    mitigation: "Increase memory limit, restart pod, scale horizontally",
    permanentFix: "Right-size limits from load testing; add HPA on memory-aware metrics",
    prevention: "Load test before production; set requests/limits from profiling data",
  },
  {
    id: "rag-hallucination",
    skillId: "rag",
    title: "RAG Hallucination Despite Retrieval",
    symptom: "Answers cite wrong documents or invent facts",
    evidence: ["Low retrieval scores", "Chunks missing key context", "No citation validation"],
    rootCause: "Poor chunking strategy or insufficient reranking",
    mitigation: "Add confidence threshold; return 'I don't know' below threshold",
    permanentFix: "Improve chunking, add reranker, implement evaluation harness",
    prevention: "Continuous RAG eval with golden Q&A sets",
  },
  {
    id: "llm-rate-limit",
    skillId: "llms",
    title: "LLM Provider Rate Limit",
    symptom: "429 errors spike, latency increases",
    evidence: ["Provider dashboard shows throttling", "Retry storms in logs"],
    rootCause: "Burst traffic exceeds provider quota without backoff",
    mitigation: "Enable exponential backoff, queue requests, switch to fallback model",
    permanentFix: "LLM gateway with rate limiting, caching, and multi-provider routing",
    prevention: "Capacity planning; cache frequent queries; self-host for steady load",
  },
];

export const CAREER_TRANSITIONS: CareerTransition[] = [
  {
    from: "devops-engineer",
    to: "mlops-engineer",
    sharedFoundation: ["Linux", "Docker", "Kubernetes", "CI/CD", "Terraform", "Cloud"],
    additionalSkills: ["Python for ML", "MLflow", "ML lifecycle", "Model serving", "ML monitoring"],
    skipIfKnown: ["Linux", "Docker", "Kubernetes", "CI/CD", "Terraform"],
    path: ["Python for AI", "ML Fundamentals", "MLflow", "Model Serving", "MLOps Pipeline", "KServe"],
  },
  {
    from: "software-developer",
    to: "ai-engineer",
    sharedFoundation: ["Python", "APIs", "Git", "SQL"],
    additionalSkills: ["LLM APIs", "RAG", "Vector DBs", "LangChain", "Agents"],
    skipIfKnown: ["Python", "Git", "REST APIs"],
    path: ["LLM APIs", "Prompt Engineering", "RAG", "Vector DB", "LangChain", "Agents", "MCP"],
  },
  {
    from: "mlops-engineer",
    to: "llmops-engineer",
    sharedFoundation: ["Python", "Docker", "Kubernetes", "CI/CD", "Monitoring"],
    additionalSkills: ["RAG", "Vector DBs", "LLM evaluation", "Prompt management", "vLLM"],
    skipIfKnown: ["Python", "Kubernetes", "Prometheus", "Docker"],
    path: ["LLM Fundamentals", "RAG Architecture", "Vector DBs", "LLM Eval", "LLM Serving", "Cost Optimization"],
  },
];

export const COMPARE_SLUGS = [
  "mlops-vs-llmops",
  "mlops-vs-ai-infrastructure",
  "devops-vs-mlops",
  "ai-engineer-vs-mlops",
  "llmops-vs-ai-engineer",
] as const;

export type CompareSlug = (typeof COMPARE_SLUGS)[number];

export const COMPARE_PAIRS: Record<CompareSlug, [string, string]> = {
  "mlops-vs-llmops": ["mlops-engineer", "llmops-engineer"],
  "mlops-vs-ai-infrastructure": ["mlops-engineer", "ai-infrastructure-engineer"],
  "devops-vs-mlops": ["devops-engineer", "mlops-engineer"],
  "ai-engineer-vs-mlops": ["ai-engineer", "mlops-engineer"],
  "llmops-vs-ai-engineer": ["llmops-engineer", "ai-engineer"],
};

export const STARTING_POINTS = [
  { id: "software-developer", label: "Software Developer" },
  { id: "devops-engineer", label: "DevOps Engineer" },
  { id: "cloud-engineer", label: "Cloud Engineer" },
  { id: "sre", label: "SRE" },
  { id: "data-engineer", label: "Data Engineer" },
  { id: "ml-engineer", label: "ML Engineer" },
  { id: "beginner", label: "Beginner / Non-Technical" },
] as const;

export const TARGET_ROLES = ROLES.map((r) => ({ id: r.id, label: r.name }));
