/** High-traffic AI/ML/DevOps engineer job profiles for the resume prep service. */

export type ResumeRole = {
  slug: string;
  title: string;
  shortTitle: string;
  category: "AI" | "ML" | "DevOps" | "Data" | "Cloud";
  salaryIndia: string;
  salaryGlobal: string;
  traffic: "ultra" | "high" | "medium";
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
  h1: string;
  intro: string;
  mustHaves: string[];
  differentiators: string[];
  portfolioProjects: { title: string; stack: string; impact: string }[];
  atsKeywords: string[];
  mistakes: string[];
  bulletTemplates: string[];
  relatedRoadmap?: string;
};

export const RESUME_ROLES: ResumeRole[] = [
  {
    slug: "mlops-engineer-resume",
    title: "MLOps Engineer Resume",
    shortTitle: "MLOps Engineer",
    category: "ML",
    salaryIndia: "₹12–40 LPA",
    salaryGlobal: "$120K–$200K",
    traffic: "ultra",
    metaTitle: "MLOps Engineer Resume Sample 2026 | ATS-Ready | Rajinikanth Vadla",
    metaDescription:
      "MLOps engineer resume writing service with role-specific bullet points, MLflow/Kubernetes/KServe keywords, portfolio projects, and ATS optimization. Built by enterprise MLOps practitioners.",
    keywords: [
      "MLOps engineer resume",
      "MLOps resume sample",
      "MLOps CV template",
      "machine learning operations resume",
      "MLflow resume",
      "Kubernetes MLOps resume",
      "MLOps resume writing",
    ],
    h1: "MLOps Engineer resume that gets shortlisted",
    intro:
      "MLOps roles sit between ML and platform engineering. Recruiters scan for ML lifecycle ownership, Kubernetes depth, and production monitoring — not model accuracy alone. We rewrite your resume to prove you ship models, not just train them.",
    mustHaves: [
      "ML pipeline ownership (training → registry → serving → monitoring)",
      "Kubernetes + Docker deployment of ML services",
      "Experiment tracking with MLflow or Weights & Biases",
      "CI/CD for models (GitHub Actions, ArgoCD, Jenkins)",
      "Drift detection and model monitoring (Evidently, Prometheus)",
    ],
    differentiators: [
      "KServe / vLLM serving at scale with autoscaling",
      "Feature store experience (Feast, Tecton)",
      "GPU scheduling and cost optimization on EKS/GKE",
      "RAG + LLM serving in addition to classical ML",
      "SLO-driven model rollout and canary deployments",
    ],
    portfolioProjects: [
      { title: "End-to-end MLOps pipeline", stack: "MLflow · DVC · Kubernetes · GitHub Actions", impact: "Cut model deployment time from 2 days to 20 minutes" },
      { title: "Drift detection service", stack: "Evidently · Prometheus · Grafana", impact: "Caught 3 production drift events before user impact" },
      { title: "Feature store on Feast", stack: "Feast · Redis · Snowflake", impact: "Served 200+ features to 5 downstream models with <50ms p99" },
    ],
    atsKeywords: ["MLOps", "ML pipeline", "MLflow", "Kubeflow", "KServe", "DVC", "Kubernetes", "Docker", "CI/CD", "Model registry", "Drift detection", "Feature store", "Prometheus", "Grafana", "AWS SageMaker", "vLLM"],
    mistakes: [
      "Listing model accuracy without deployment context",
      "No Kubernetes or containerization evidence",
      "Missing monitoring / observability tools",
      "Describing notebooks instead of production systems",
      "No CI/CD for models — only for app code",
    ],
    bulletTemplates: [
      "Built MLOps pipeline with MLflow + Kubernetes that reduced model deployment time by {X}%",
      "Deployed {N} models to production with KServe, achieving {latency} p99 latency",
      "Implemented drift detection with Evidently, catching {N} issues before user impact",
      "Owned ML infrastructure on EKS serving {N}M requests/day at {cost} cost",
    ],
    relatedRoadmap: "mlops-engineer",
  },
  {
    slug: "llmops-engineer-resume",
    title: "LLMOps Engineer Resume",
    shortTitle: "LLMOps Engineer",
    category: "AI",
    salaryIndia: "₹18–50 LPA",
    salaryGlobal: "$140K–$230K",
    traffic: "ultra",
    metaTitle: "LLMOps Engineer Resume Sample 2026 | RAG, vLLM, Guardrails | Rajinikanth Vadla",
    metaDescription:
      "LLMOps engineer resume writing service. RAG pipelines, vLLM serving, LangChain, evaluation harnesses, guardrails, cost control. ATS-ready CV built by practitioners.",
    keywords: ["LLMOps resume", "LLMOps engineer resume", "LLM engineer resume sample", "RAG resume", "vLLM resume", "LLMOps CV template", "LangChain resume"],
    h1: "LLMOps Engineer resume for production LLM roles",
    intro:
      "LLMOps is the hottest AI role in 2026. Hiring managers want RAG depth, evaluation rigor, and cost control — not prompt engineering fluff. We position your resume around shipped LLM systems.",
    mustHaves: [
      "Production RAG pipeline (chunking, embeddings, reranker, vector DB)",
      "LLM serving with vLLM, TGI, or LiteLLM gateway",
      "Evaluation harness (Ragas, DeepEval, LangSmith)",
      "Cost and latency monitoring for LLM calls",
      "Guardrails (NeMo Guardrails, Guardrails AI) for input/output safety",
    ],
    differentiators: [
      "Multi-model routing with LiteLLM (GPT, Claude, Gemini fallbacks)",
      "Fine-tuning with PEFT/LoRA on open models",
      "Vector DB selection rationale (pgvector vs Pinecone vs Weaviate)",
      "Streaming SSE responses and token-level UX",
      "MCP server integrations for tool use",
    ],
    portfolioProjects: [
      { title: "Enterprise RAG assistant", stack: "LangChain · pgvector · LiteLLM · NeMo Guardrails", impact: "Served 5K employees with 92% answer accuracy" },
      { title: "LLM cost optimization", stack: "LiteLLM · Prometheus · Langfuse", impact: "Cut monthly LLM spend by 40% via routing + caching" },
      { title: "Guardrails service", stack: "NeMo Guardrails · FastAPI · Redis", impact: "Blocked 100% of prompt injection attempts in red-team" },
    ],
    atsKeywords: ["LLMOps", "RAG", "LLM serving", "vLLM", "LiteLLM", "LangChain", "LangGraph", "Vector database", "pgvector", "Pinecone", "Weaviate", "Guardrails", "NeMo", "Evaluation", "Ragas", "LangSmith", "Prompt engineering", "Fine-tuning", "MCP"],
    mistakes: [
      "Only ChatGPT prompt experience, no production LLM system",
      "No evaluation metrics for RAG quality",
      "Missing cost / latency numbers",
      "No guardrails or safety story",
      "Listing LangChain tutorials instead of shipped features",
    ],
    bulletTemplates: [
      "Built RAG pipeline with {vector_db} + LiteLLM serving {N} queries/day at {latency} p99",
      "Implemented LLM evaluation harness with Ragas, improving answer accuracy from {X}% to {Y}%",
      "Cut LLM cost by {X}% via LiteLLM routing + semantic caching with Redis",
      "Deployed NeMo Guardrails blocking {N} prompt injection attempts in red-team testing",
    ],
    relatedRoadmap: "llmops-engineer",
  },
  {
    slug: "ai-engineer-resume",
    title: "AI Engineer Resume",
    shortTitle: "AI Engineer",
    category: "AI",
    salaryIndia: "₹15–50 LPA",
    salaryGlobal: "$120K–$220K",
    traffic: "ultra",
    metaTitle: "AI Engineer Resume Sample 2026 | LLM, RAG, Agents | Rajinikanth Vadla",
    metaDescription:
      "AI engineer resume writing service with LLM app, RAG, agent, and MCP project bullets. ATS-ready CV built by practitioners who ship production AI.",
    keywords: ["AI engineer resume", "AI engineer CV", "AI engineer resume sample", "LLM engineer resume", "AI agent resume", "RAG engineer resume", "artificial intelligence engineer resume"],
    h1: "AI Engineer resume that proves you ship LLM apps",
    intro:
      "AI Engineer is the most-searched AI role in 2026. Recruiters want shipped LLM features, agents, and RAG — not model theory. We rewrite your resume around production AI you have built.",
    mustHaves: [
      "Production LLM application (chat, search, or agent)",
      "RAG pipeline with vector database",
      "Agent framework (LangChain, LangGraph, CrewAI)",
      "FastAPI or Next.js API layer",
      "Evaluation and prompt management",
    ],
    differentiators: [
      "MCP server integrations for tool use",
      "Multi-agent orchestration with LangGraph",
      "Streaming SSE responses and token-level UX",
      "Fine-tuning open models (Llama, Mistral)",
      "Vector DB selection rationale and hybrid search",
    ],
    portfolioProjects: [
      { title: "Customer support AI agent", stack: "LangGraph · pgvector · FastAPI · OpenAI", impact: "Resolved 60% of tier-1 tickets autonomously" },
      { title: "Internal RAG search", stack: "LangChain · Pinecone · LiteLLM", impact: "Served 2K employees with sub-second retrieval" },
      { title: "MCP tool integrations", stack: "MCP · GitHub · Slack · LangChain", impact: "Automated 5 engineering workflows, saving 10 hrs/week" },
    ],
    atsKeywords: ["AI Engineer", "LLM", "RAG", "LangChain", "LangGraph", "CrewAI", "MCP", "Vector database", "FastAPI", "Prompt engineering", "AI agents", "OpenAI", "Anthropic", "Gemini", "HuggingFace", "Fine-tuning"],
    mistakes: [
      "Only course projects, no shipped AI feature",
      "No evaluation or testing of LLM outputs",
      "Listing prompt engineering without production context",
      "Missing API / backend layer (FastAPI, Next.js)",
      "No vector DB or retrieval evidence",
    ],
    bulletTemplates: [
      "Built AI agent with LangGraph handling {N} user intents, automating {X}% of workflow",
      "Shipped RAG feature with {vector_db} serving {N} docs at {latency} p99",
      "Integrated {N} MCP servers for tool use, automating {hours} hrs/week of manual work",
      "Deployed LLM app on FastAPI + Next.js with {N} daily active users",
    ],
    relatedRoadmap: "ai-engineer",
  },
  {
    slug: "ml-engineer-resume",
    title: "ML Engineer Resume",
    shortTitle: "ML Engineer",
    category: "ML",
    salaryIndia: "₹10–45 LPA",
    salaryGlobal: "$110K–$190K",
    traffic: "ultra",
    metaTitle: "ML Engineer Resume Sample 2026 | PyTorch, scikit-learn, MLOps | Rajinikanth Vadla",
    metaDescription:
      "ML engineer resume writing service. PyTorch, scikit-learn, model deployment, feature engineering bullets. ATS-ready CV built by practitioners.",
    keywords: ["ML engineer resume", "machine learning engineer resume", "ML engineer CV", "ML engineer resume sample", "PyTorch resume", "scikit-learn resume", "ML engineer resume writing"],
    h1: "ML Engineer resume that proves production impact",
    intro:
      "ML Engineer resumes fail when they list libraries without deployment. Hiring managers want models in production with measurable impact. We rewrite yours around shipped ML systems.",
    mustHaves: [
      "Model training with PyTorch / scikit-learn / XGBoost",
      "Feature engineering and data pipelines",
      "Model deployment (FastAPI, SageMaker, KServe)",
      "Evaluation metrics tied to business KPIs",
      "Versioning with DVC or MLflow",
    ],
    differentiators: [
      "Distributed training with Ray or Horovod",
      "Online vs batch scoring tradeoffs",
      "A/B testing framework for model rollout",
      "Classical ML + LLM hybrid systems",
      "GPU training and inference optimization",
    ],
    portfolioProjects: [
      { title: "Fraud detection model", stack: "PyTorch · SageMaker · MLflow", impact: "Reduced false positives by 35%, saving ₹2Cr/year" },
      { title: "Demand forecasting", stack: "XGBoost · Airflow · Feast", impact: "Improved forecast accuracy by 18% across 200 SKUs" },
      { title: "Recommendation system", stack: "scikit-learn · Redis · FastAPI", impact: "Lifted CTR by 22% for 5M users" },
    ],
    atsKeywords: ["Machine Learning", "ML Engineer", "PyTorch", "TensorFlow", "scikit-learn", "XGBoost", "Pandas", "NumPy", "MLflow", "DVC", "SageMaker", "Feature engineering", "Model deployment", "A/B testing", "MLOps"],
    mistakes: [
      "Listing Kaggle competitions only",
      "No deployment or serving evidence",
      "Missing business metrics (accuracy without impact)",
      "No versioning or experiment tracking",
      "Describing notebooks instead of pipelines",
    ],
    bulletTemplates: [
      "Trained {model} with PyTorch, improving {metric} by {X}% on {dataset}",
      "Deployed ML service on {platform} serving {N} predictions/day at {latency} p99",
      "Built feature pipeline with {tool}, reducing feature prep time by {X}%",
      "A/B tested model rollout, lifting {business_metric} by {X}%",
    ],
    relatedRoadmap: "ai-ml-engineer",
  },
  {
    slug: "data-scientist-resume",
    title: "Data Scientist Resume",
    shortTitle: "Data Scientist",
    category: "Data",
    salaryIndia: "₹8–35 LPA",
    salaryGlobal: "$100K–$170K",
    traffic: "ultra",
    metaTitle: "Data Scientist Resume Sample 2026 | Python, SQL, Stats, ML | Rajinikanth Vadla",
    metaDescription:
      "Data scientist resume writing service with statistics, Python, SQL, ML, and business impact bullets. ATS-ready CV built by practitioners.",
    keywords: ["data scientist resume", "data scientist CV", "data scientist resume sample", "data scientist resume writing", "Python data scientist resume", "SQL data scientist resume", "entry level data scientist resume"],
    h1: "Data Scientist resume that proves business impact",
    intro:
      "Data Scientist resumes fail when they list tools without business outcomes. Hiring managers want statistical rigor, SQL fluency, and measurable impact. We rewrite yours around decisions you drove.",
    mustHaves: [
      "Python (pandas, NumPy, scikit-learn)",
      "SQL and data wrangling at scale",
      "Statistics — experimentation, A/B testing, causal inference",
      "ML modeling with business metric tie-in",
      "Stakeholder communication and dashboards",
    ],
    differentiators: [
      "Causal inference and uplift modeling",
      "Experiment design and sample size calculation",
      "Storytelling with data (Tableau, Looker, Streamlit)",
      "Production handoff to ML / MLOps teams",
      "Domain depth (fintech, retail, healthcare)",
    ],
    portfolioProjects: [
      { title: "Churn prediction model", stack: "Python · scikit-learn · BigQuery", impact: "Identified 12% of at-risk users, enabling retention campaign" },
      { title: "A/B testing framework", stack: "Python · SciPy · Streamlit", impact: "Standardized experiment readout across 4 product teams" },
      { title: "Pricing elasticity study", stack: "Python · statsmodels · SQL", impact: "Informed 8% price increase with no churn impact" },
    ],
    atsKeywords: ["Data Scientist", "Python", "SQL", "Statistics", "A/B testing", "Pandas", "NumPy", "scikit-learn", "Causal inference", "Tableau", "Looker", "Machine Learning", "Experimentation", "Storytelling"],
    mistakes: [
      "Listing tools without business outcomes",
      "No SQL or data wrangling evidence",
      "Missing statistical rigor",
      "No stakeholder or communication story",
      "Describing models without deployment handoff",
    ],
    bulletTemplates: [
      "Built churn model with scikit-learn, identifying {X}% of at-risk users and enabling retention",
      "Designed A/B testing framework adopted by {N} product teams",
      "Analyzed {N}M rows in BigQuery, informing {decision} that lifted {metric} by {X}%",
      "Built causal inference study that justified {business_decision}",
    ],
  },
  {
    slug: "devops-engineer-resume",
    title: "DevOps Engineer Resume",
    shortTitle: "DevOps Engineer",
    category: "DevOps",
    salaryIndia: "₹8–35 LPA",
    salaryGlobal: "$100K–$180K",
    traffic: "ultra",
    metaTitle: "DevOps Engineer Resume Sample 2026 | Kubernetes, Terraform, CI/CD | Rajinikanth Vadla",
    metaDescription:
      "DevOps engineer resume writing service with Kubernetes, Terraform, CI/CD, observability, and cloud bullets. ATS-ready CV built by practitioners.",
    keywords: ["DevOps engineer resume", "DevOps resume sample", "DevOps CV template", "Kubernetes resume", "Terraform resume", "CI/CD resume", "DevOps resume writing"],
    h1: "DevOps Engineer resume that proves reliability and automation",
    intro:
      "DevOps roles want proof of automation, reliability, and cloud depth. We rewrite your resume around pipelines you built, incidents you reduced, and infrastructure you automated.",
    mustHaves: [
      "CI/CD pipelines (GitHub Actions, GitLab, Jenkins)",
      "Kubernetes + Docker in production",
      "Infrastructure as Code (Terraform, Pulumi)",
      "Cloud (AWS, Azure, GCP) with hands-on services",
      "Observability (Prometheus, Grafana, ELK, Datadog)",
    ],
    differentiators: [
      "GitOps with ArgoCD or Flux",
      "Service mesh (Istio, Linkerd)",
      "Policy as code (OPA, Kyverno)",
      "Platform engineering and internal developer portals",
      "Multi-cloud or hybrid deployment experience",
    ],
    portfolioProjects: [
      { title: "GitOps migration", stack: "ArgoCD · Kubernetes · GitHub Actions", impact: "Cut deployment lead time from 2 hours to 10 minutes" },
      { title: "Terraform module library", stack: "Terraform · AWS · Atlantis", impact: "Standardized 40+ resources across 5 teams" },
      { title: "Observability stack", stack: "Prometheus · Grafana · Loki", impact: "Reduced MTTR by 50% via better dashboards and alerts" },
    ],
    atsKeywords: ["DevOps", "Kubernetes", "Docker", "Terraform", "CI/CD", "GitHub Actions", "Jenkins", "ArgoCD", "AWS", "Azure", "GCP", "Prometheus", "Grafana", "Linux", "Helm", "GitOps", "SRE"],
    mistakes: [
      "Listing tools without automation outcomes",
      "No incident or reliability metrics",
      "Missing IaC evidence",
      "Describing manual deployments",
      "No cloud platform depth",
    ],
    bulletTemplates: [
      "Built CI/CD pipeline with GitHub Actions, cutting deployment time by {X}%",
      "Migrated {N} services to Kubernetes with zero downtime",
      "Authored Terraform modules standardizing {N} resources across teams",
      "Reduced MTTR by {X}% via Prometheus + Grafana observability stack",
    ],
  },
  {
    slug: "data-engineer-resume",
    title: "Data Engineer Resume",
    shortTitle: "Data Engineer",
    category: "Data",
    salaryIndia: "₹8–30 LPA",
    salaryGlobal: "$100K–$170K",
    traffic: "high",
    metaTitle: "Data Engineer Resume Sample 2026 | Spark, Airflow, SQL, Cloud | Rajinikanth Vadla",
    metaDescription:
      "Data engineer resume writing service with Spark, Airflow, SQL, cloud data warehouse, and pipeline bullets. ATS-ready CV built by practitioners.",
    keywords: ["data engineer resume", "data engineer CV", "data engineer resume sample", "Spark resume", "Airflow resume", "data pipeline resume", "data engineer resume writing"],
    h1: "Data Engineer resume that proves pipeline ownership",
    intro:
      "Data Engineer resumes fail when they list tools without pipeline scale. Hiring managers want ETL ownership, data quality, and warehouse depth. We rewrite yours around pipelines you shipped.",
    mustHaves: [
      "SQL + Python for data wrangling",
      "Orchestration (Airflow, Prefect, Dagster)",
      "Batch + stream processing (Spark, Flink, Kafka)",
      "Cloud data warehouse (Snowflake, BigQuery, Redshift)",
      "Data quality and observability",
    ],
    differentiators: [
      "Real-time streaming with Kafka + Flink",
      "Lakehouse architecture (Delta, Iceberg, Hudi)",
      "Data mesh / domain-oriented ownership",
      "Cost optimization on warehouse spend",
      "Self-serve data platform tooling",
    ],
    portfolioProjects: [
      { title: "Streaming ETL pipeline", stack: "Kafka · Flink · Snowflake", impact: "Processed 1M events/min with 99.9% delivery" },
      { title: "Airflow migration", stack: "Airflow · dbt · BigQuery", impact: "Replaced 200 cron jobs with 40 DAGs" },
      { title: "Lakehouse on Delta", stack: "Spark · Delta Lake · S3", impact: "Unified batch + ML workloads, cutting storage cost 30%" },
    ],
    atsKeywords: ["Data Engineer", "Spark", "Airflow", "Kafka", "SQL", "Python", "Snowflake", "BigQuery", "Redshift", "dbt", "Flink", "Delta Lake", "Iceberg", "ETL", "Data pipeline", "Cloud warehouse"],
    mistakes: [
      "Listing SQL without pipeline scale",
      "No orchestration tool evidence",
      "Missing data quality story",
      "Describing one-off scripts instead of pipelines",
      "No cloud warehouse depth",
    ],
    bulletTemplates: [
      "Built streaming pipeline with Kafka + Flink processing {N} events/min",
      "Migrated {N} cron jobs to Airflow DAGs, improving reliability by {X}%",
      "Designed lakehouse on Delta Lake, unifying {N} workloads and cutting storage {X}%",
      "Owned dbt + BigQuery stack serving {N} downstream consumers",
    ],
  },
  {
    slug: "platform-engineer-resume",
    title: "Platform Engineer Resume",
    shortTitle: "Platform Engineer",
    category: "DevOps",
    salaryIndia: "₹15–45 LPA",
    salaryGlobal: "$130K–$220K",
    traffic: "high",
    metaTitle: "Platform Engineer Resume Sample 2026 | Backstage, K8s, IDP | Rajinikanth Vadla",
    metaDescription:
      "Platform engineer resume writing service with internal developer portal, Backstage, Kubernetes, and golden-path bullets. ATS-ready CV built by practitioners.",
    keywords: ["platform engineer resume", "platform engineering resume", "platform engineer CV", "Backstage resume", "internal developer portal resume", "platform engineer resume sample"],
    h1: "Platform Engineer resume that proves developer experience impact",
    intro:
      "Platform Engineering is the fastest-growing DevOps track in 2026. Hiring managers want internal developer portals, golden paths, and DX metrics. We rewrite yours around platforms you built.",
    mustHaves: [
      "Kubernetes + container platform ownership",
      "Internal Developer Portal (Backstage, Port)",
      "Golden-path templates and scaffolding",
      "Self-serve infrastructure for product teams",
      "DX metrics (lead time, deployment frequency, MTTR)",
    ],
    differentiators: [
      "Backstage plugin development",
      "Crossplane for self-serve infrastructure",
      "Policy as code (OPA, Kyverno) on the platform",
      "Cost visibility and FinOps integration",
      "Multi-tenant platform with namespace isolation",
    ],
    portfolioProjects: [
      { title: "Backstage IDP rollout", stack: "Backstage · Kubernetes · ArgoCD", impact: "Onboarded 12 teams, cutting service creation from 2 weeks to 2 hours" },
      { title: "Golden-path templates", stack: "Crossplane · Helm · GitHub Actions", impact: "Standardized 80% of new service bootstraps" },
      { title: "Platform cost dashboard", stack: "Grafana · Kubecost · BigQuery", impact: "Identified 25% waste, saving ₹40K/month" },
    ],
    atsKeywords: ["Platform Engineer", "Platform engineering", "Backstage", "Internal Developer Portal", "Kubernetes", "Crossplane", "Helm", "ArgoCD", "OPA", "Kyverno", "DX", "Golden path", "GitOps", "FinOps"],
    mistakes: [
      "Describing DevOps work without platform framing",
      "No IDP or self-serve evidence",
      "Missing DX metrics",
      "Listing tools without platform ownership",
      "No multi-tenant or cost story",
    ],
    bulletTemplates: [
      "Rolled out Backstage IDP onboarding {N} teams, cutting service creation from {X} to {Y}",
      "Built golden-path templates with Crossplane, standardizing {X}% of new services",
      "Authored OPA policies enforcing {N} compliance controls across the platform",
      "Implemented Kubecost dashboard identifying {X}% waste, saving {cost}/month",
    ],
  },
  {
    slug: "ai-infrastructure-engineer-resume",
    title: "AI Infrastructure Engineer Resume",
    shortTitle: "AI Infra Engineer",
    category: "Cloud",
    salaryIndia: "₹15–40 LPA",
    salaryGlobal: "$130K–$210K",
    traffic: "high",
    metaTitle: "AI Infrastructure Engineer Resume 2026 | GPU, vLLM, K8s | Rajinikanth Vadla",
    metaDescription:
      "AI infrastructure engineer resume writing service with GPU scheduling, vLLM, distributed training, and inference serving bullets. ATS-ready CV.",
    keywords: ["AI infrastructure resume", "AI infra engineer resume", "GPU engineer resume", "vLLM resume", "inference serving resume", "AI infrastructure CV"],
    h1: "AI Infrastructure Engineer resume for GPU + inference roles",
    intro:
      "AI Infra roles want GPU depth, distributed training, and inference serving at scale. We rewrite yours around clusters you built and cost you optimized.",
    mustHaves: [
      "GPU cluster management on Kubernetes",
      "Inference serving (vLLM, TGI, Triton)",
      "Distributed training (Ray, MPI, Horovod)",
      "Storage and networking for AI workloads",
      "Cost and utilization optimization",
    ],
    differentiators: [
      "NVIDIA GPU operator and MIG partitioning",
      "NCCL and RDMA tuning for multi-node training",
      "Spot/preemptible GPU strategy",
      "Multi-tenant GPU scheduling",
      "FinOps for GPU spend",
    ],
    portfolioProjects: [
      { title: "GPU cluster on GKE", stack: "GKE · NVIDIA Operator · vLLM", impact: "Served 50M tokens/day at 40% lower cost than managed endpoints" },
      { title: "Distributed training platform", stack: "Ray · NCCL · S3", impact: "Trained 70B model across 32 GPUs with 90% scaling efficiency" },
      { title: "Inference cost optimization", stack: "vLLM · Kubecost · Prometheus", impact: "Cut GPU spend 35% via batching + MIG partitioning" },
    ],
    atsKeywords: ["AI Infrastructure", "GPU", "Kubernetes", "vLLM", "Triton", "Ray", "NCCL", "NVIDIA", "Distributed training", "Inference serving", "MIG", "FinOps", "CUDA", "EKS", "GKE"],
    mistakes: [
      "No GPU or distributed training evidence",
      "Missing inference serving depth",
      "No cost or utilization numbers",
      "Describing app deployment instead of AI infra",
      "No multi-node or NCCL story",
    ],
    bulletTemplates: [
      "Built GPU cluster on {platform} serving {N}M tokens/day at {cost} cost",
      "Trained {model} across {N} GPUs with {X}% scaling efficiency",
      "Cut inference cost {X}% via vLLM batching + MIG partitioning",
      "Owned AI infra for {N} teams, supporting {N} GPUs in production",
    ],
    relatedRoadmap: "ai-infrastructure-engineer",
  },
  {
    slug: "cloud-engineer-resume",
    title: "Cloud Engineer Resume",
    shortTitle: "Cloud Engineer",
    category: "Cloud",
    salaryIndia: "₹8–30 LPA",
    salaryGlobal: "$100K–$170K",
    traffic: "high",
    metaTitle: "Cloud Engineer Resume Sample 2026 | AWS, Azure, GCP, Terraform | Rajinikanth Vadla",
    metaDescription:
      "Cloud engineer resume writing service with AWS, Azure, GCP, Terraform, networking, and security bullets. ATS-ready CV built by practitioners.",
    keywords: ["cloud engineer resume", "cloud engineer CV", "AWS resume", "Azure resume", "GCP resume", "cloud engineer resume sample", "cloud resume writing"],
    h1: "Cloud Engineer resume that proves cloud depth",
    intro:
      "Cloud Engineer resumes fail when they list certifications without hands-on services. Hiring managers want VPC, IAM, and IaC depth. We rewrite yours around cloud you built.",
    mustHaves: [
      "AWS or Azure or GCP core services (compute, storage, networking)",
      "Terraform or Pulumi IaC",
      "IAM, VPC, and security groups",
      "Cost monitoring and optimization",
      "CI/CD for infrastructure",
    ],
    differentiators: [
      "Multi-cloud or hybrid experience",
      "Landing zone and org-level IAM design",
      "Disaster recovery and multi-region",
      "FinOps and cost visibility tooling",
      "Well-Architected reviews",
    ],
    portfolioProjects: [
      { title: "Landing zone on AWS", stack: "Terraform · AWS Organizations · Control Tower", impact: "Standardized 50+ accounts with guardrails" },
      { title: "Multi-region DR", stack: "Azure · Traffic Manager · Terraform", impact: "Achieved RTO 15 min and RPO 5 min for 20 services" },
      { title: "Cost optimization", stack: "AWS Cost Explorer · Kubecost · Lambda", impact: "Cut monthly cloud spend 22% via rightsizing" },
    ],
    atsKeywords: ["Cloud Engineer", "AWS", "Azure", "GCP", "Terraform", "Pulumi", "VPC", "IAM", "EC2", "S3", "RDS", "Lambda", "Kubernetes", "FinOps", "Disaster recovery", "Well-Architected"],
    mistakes: [
      "Listing certifications without hands-on services",
      "No IaC evidence",
      "Missing networking or IAM depth",
      "No cost or optimization story",
      "Describing console clicks instead of automation",
    ],
    bulletTemplates: [
      "Built landing zone with Terraform standardizing {N} accounts with guardrails",
      "Designed multi-region DR achieving RTO {X} min and RPO {Y} min",
      "Cut cloud spend {X}% via rightsizing and Kubecost visibility",
      "Owned IAM for {N} teams with policy-as-code on OPA",
    ],
  },
  {
    slug: "genai-engineer-resume",
    title: "GenAI Engineer Resume",
    shortTitle: "GenAI Engineer",
    category: "AI",
    salaryIndia: "₹15–50 LPA",
    salaryGlobal: "$130K–$220K",
    traffic: "high",
    metaTitle: "GenAI Engineer Resume Sample 2026 | LLM, Fine-tuning, RAG | Rajinikanth Vadla",
    metaDescription:
      "GenAI engineer resume writing service with LLM fine-tuning, RAG, prompt engineering, and production GenAI bullets. ATS-ready CV built by practitioners.",
    keywords: ["GenAI engineer resume", "generative AI resume", "GenAI CV", "LLM engineer resume sample", "fine-tuning resume", "GenAI resume writing"],
    h1: "GenAI Engineer resume for LLM + generative AI roles",
    intro:
      "GenAI Engineer roles want fine-tuning depth, RAG production, and prompt management. We rewrite yours around generative AI you shipped, not just prompted.",
    mustHaves: [
      "LLM application in production (chat, search, or content)",
      "RAG pipeline with vector database",
      "Prompt engineering and prompt registry",
      "Fine-tuning (PEFT, LoRA, QLoRA) on open models",
      "Evaluation and guardrails",
    ],
    differentiators: [
      "Multi-modal GenAI (text + image + audio)",
      "Custom inference stack with vLLM",
      "Cost optimization via model routing",
      "Domain-specific fine-tuning",
      "Responsible AI and safety reviews",
    ],
    portfolioProjects: [
      { title: "Fine-tuned Llama for support", stack: "LoRA · HuggingFace · vLLM", impact: "Cut support cost 30% with on-prem fine-tuned model" },
      { title: "Multi-modal search", stack: "CLIP · pgvector · FastAPI", impact: "Unified text + image search for 1M assets" },
      { title: "Prompt registry", stack: "LangSmith · LiteLLM · Redis", impact: "Versioned 200 prompts with rollback support" },
    ],
    atsKeywords: ["GenAI", "Generative AI", "LLM", "Fine-tuning", "LoRA", "QLoRA", "RAG", "Prompt engineering", "HuggingFace", "vLLM", "LangSmith", "Llama", "Mistral", "Multi-modal", "Guardrails"],
    mistakes: [
      "Only ChatGPT prompting, no production GenAI",
      "No fine-tuning or custom model work",
      "Missing evaluation metrics",
      "No cost or latency numbers",
      "Listing prompt courses instead of shipped features",
    ],
    bulletTemplates: [
      "Fine-tuned {model} with LoRA, cutting support cost {X}% with on-prem serving",
      "Built multi-modal search with CLIP + {vector_db} for {N} assets",
      "Versioned {N} prompts in LangSmith with rollback and A/B testing",
      "Deployed GenAI feature on vLLM serving {N} requests/day at {latency} p99",
    ],
  },
  {
    slug: "nlp-engineer-resume",
    title: "NLP Engineer Resume",
    shortTitle: "NLP Engineer",
    category: "AI",
    salaryIndia: "₹10–40 LPA",
    salaryGlobal: "$110K–$190K",
    traffic: "high",
    metaTitle: "NLP Engineer Resume Sample 2026 | Transformers, BERT, LLMs | Rajinikanth Vadla",
    metaDescription:
      "NLP engineer resume writing service with transformers, BERT, NER, sentiment, and LLM bullets. ATS-ready CV built by practitioners.",
    keywords: ["NLP engineer resume", "NLP resume", "NLP CV", "NLP engineer resume sample", "transformer resume", "BERT resume", "NLP resume writing"],
    h1: "NLP Engineer resume for transformer + LLM roles",
    intro:
      "NLP roles want transformer depth, NER/RE production, and LLM fine-tuning. We rewrite yours around NLP systems you shipped, not just notebooks.",
    mustHaves: [
      "Transformers (BERT, RoBERTa, T5, GPT)",
      "Tokenization and text preprocessing",
      "NER, sentiment, classification in production",
      "HuggingFace + fine-tuning",
      "Evaluation (F1, BLEU, ROUGE)",
    ],
    differentiators: [
      "Custom transformer training",
      "Domain adaptation with continued pretraining",
      "RAG with NLP preprocessing",
      "Multilingual NLP",
      "LLM fine-tuning for NLP tasks",
    ],
    portfolioProjects: [
      { title: "NER for legal docs", stack: "BERT · HuggingFace · FastAPI", impact: "Extracted 50+ entity types with 92% F1" },
      { title: "Sentiment at scale", stack: "RoBERTa · Kafka · Redis", impact: "Processed 5M reviews/day for product insights" },
      { title: "Multilingual search", stack: "Sentence-Transformers · pgvector", impact: "Unified 12-language search for 2M docs" },
    ],
    atsKeywords: ["NLP", "Natural Language Processing", "Transformers", "BERT", "RoBERTa", "T5", "HuggingFace", "NER", "Sentiment", "Tokenization", "BLEU", "ROUGE", "Sentence-Transformers", "Fine-tuning"],
    mistakes: [
      "Only course NLP, no production system",
      "No evaluation metrics",
      "Missing transformer depth",
      "Describing spaCy tutorials only",
      "No LLM or fine-tuning evidence",
    ],
    bulletTemplates: [
      "Built NER with BERT extracting {N} entity types at {X}% F1",
      "Processed {N}M reviews/day with RoBERTa for sentiment classification",
      "Fine-tuned {model} on domain data, lifting {metric} by {X}%",
      "Deployed multilingual search with Sentence-Transformers for {N} docs",
    ],
    relatedRoadmap: "nlp-engineer",
  },
  {
    slug: "sre-resume",
    title: "Site Reliability Engineer Resume",
    shortTitle: "SRE",
    category: "DevOps",
    salaryIndia: "₹12–40 LPA",
    salaryGlobal: "$120K–$200K",
    traffic: "high",
    metaTitle: "SRE Resume Sample 2026 | SLO, SLI, Incident, Toil | Rajinikanth Vadla",
    metaDescription:
      "Site reliability engineer resume writing service with SLO/SLI, incident management, toil reduction, and observability bullets. ATS-ready CV.",
    keywords: ["SRE resume", "site reliability engineer resume", "SRE CV", "SRE resume sample", "SLO resume", "reliability engineer resume"],
    h1: "SRE resume that proves reliability outcomes",
    intro:
      "SRE roles want SLO/SLI design, incident reduction, and toil elimination. We rewrite yours around reliability you measured and improved.",
    mustHaves: [
      "SLO/SLI design and error budgets",
      "Incident response and postmortems",
      "Observability (Prometheus, Grafana, OTel)",
      "Toil reduction via automation",
      "On-call and runbooks",
    ],
    differentiators: [
      "Chaos engineering (Gremlin, Litmus)",
      "Capacity planning and load testing",
      "Multi-region failover design",
      "Service mesh and mTLS",
      "Cost-aware reliability",
    ],
    portfolioProjects: [
      { title: "SLO rollout", stack: "Prometheus · Grafana · Sloth", impact: "Defined SLOs for 30 services, cutting user-facing incidents 40%" },
      { title: "Runbook automation", stack: "Python · Ansible · PagerDuty", impact: "Reduced MTTR from 45 to 12 minutes" },
      { title: "Chaos testing", stack: "Litmus · Kubernetes · Grafana", impact: "Found 5 failure modes before production impact" },
    ],
    atsKeywords: ["SRE", "Site Reliability", "SLO", "SLI", "Error budget", "Incident response", "Postmortem", "Prometheus", "Grafana", "OpenTelemetry", "Toil", "Runbook", "On-call", "Chaos engineering", "MTTR"],
    mistakes: [
      "No SLO or SLI evidence",
      "Missing incident metrics",
      "Listing tools without reliability outcomes",
      "No automation or toil reduction story",
      "Describing DevOps without SRE framing",
    ],
    bulletTemplates: [
      "Defined SLOs for {N} services, cutting user-facing incidents by {X}%",
      "Reduced MTTR from {X} to {Y} minutes via runbook automation",
      "Ran chaos testing finding {N} failure modes before production impact",
      "Owned observability stack on Prometheus + Grafana for {N} services",
    ],
  },
];
